# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "linux_venv_main" ]
  pull_request:
    branches: [ "linux_venv_main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest
    - name: Pip Installer
  # You may pin to the exact commit or the version.
  # uses: BSFishy/pip-action@8f2d471d809dc20b6ada98c91910b6ae6243f318
  uses: BSFishy/pip-action@v1
  with:
    # The packages to install from Pip
    packages: pyqt5, pyqt5-tools, mysql-connector # optional, default is 
    # A requirements file to install from
    requirements: # optional, default is 
    # A constraints file to use
    constraints: # optional, default is 
    # Don't install package dependencies
    no-deps: # optional, default is false
    # Include prerelease and development versions
    pre: # optional, default is false
    # Install a project in editable mode
    editable: # optional, default is 
    # Only use wheels compatible with a specific platform
    platform: # optional, default is 
    # Upgrade all specified packages to the newest available version
    upgrade: # optional, default is false
    # Extra inputs to pass to pip
    extra: # optional, default is 
